services:
  backend:
    image: webdevops/php-nginx-dev:8.4
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    command: >-
      sh -c "cd /var/www/html && 
            composer install --no-interaction && 
            php-fpm & 
            nginx -g 'daemon off;'"
    environment:
      MYSQL_HOST: acadalyze-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: acadalyze
      WEB_DOCUMENT_ROOT: /var/www/html/public

  acadalyze-mysql:
    image: mysql:8.0
    container_name: acadalyze-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acadalyze
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/docker/mysql-init:/docker-entrypoint-initdb.d  # Auto-runs SQL files

  acadalyze-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: acadalyze-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: acadalyze-mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - acadalyze-mysql

volumes:
  mysql-data: